import Drawer from "@/components/Drawer";
import NonSSRWrapper from "@/components/NonSSRWrapper";
import Provider from "@/components/Provider";
import BrowserNavBar from "@/components/navbar/BrowserNavBar";
import "@/styles/globals.css";
import { Capacitor } from "@capacitor/core";
import { ThemeProvider, createTheme } from "@mui/material";
import type { AppProps } from "next/app";
import Head from "next/head";

const theme = createTheme({
  palette: {
    primary: {
      light: "#EEEEEE",
      main: "#622fb4",
      dark: "#80C4E4",
      contrastText: "#F4F6F6",
    },
    secondary: {
      light: "#828385",
      main: "#52565E",
      dark: "#C0C3C9",
      contrastText: "#F4F6F6",
    },
    action: {
      disabledBackground: "#80C4E4",
      disabled: "#F4F6F6",
    },
  },
  // components: {
  //   MuiInputLabel: {
  //     styleOverrides: {
  //       root: {
  //         color: "#FFF",
  //       },
  //     },
  //   },
  //   MuiOutlinedInput: {
  //     styleOverrides: {
  //       root: {
  //         color: "#fff",
  //         background: "#2B2E32",
  //       },
  //     },
  //   },
  // },
});
export const metadata: any = {
  title: "Athena App",
  description: "Generated by create next app",
};

export const viewport: any = {
  initialScale: 1,
  width: "device-width",
  viewportFit: "cover",
};

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Athena App</title>
        <meta name="description" content="Mar app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, viewport-fit=cover"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={theme}>
        <NonSSRWrapper>
          <Provider>
            <div
              className={`inline-flex justify-center bg-white flex-col items-center w-full h-[100vh] md:w-full`}
            >
              <Drawer />
              {!Capacitor.isNativePlatform() && <BrowserNavBar />}
              <div className={` w-full h-full max-w-md md:w-full`}>
                <Component {...pageProps} />
              </div>
            </div>
          </Provider>
        </NonSSRWrapper>
      </ThemeProvider>
    </>
  );
}
